version: '2'
services:
  zk-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-1
    ports:
      - "13181:13181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 13181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:13888:14888;zk-2:23888:24888;zk-3:33888:34888
    networks:
      - proxy

  zk-2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-2
    ports:
      - "23181:23181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 23181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:13888:14888;zk-2:23888:24888;zk-3:33888:34888
    networks:
      - proxy

  zk-3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-3
    ports:
      - "33181:33181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 33181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:13888:14888;zk-2:23888:24888;zk-3:33888:34888
    networks:
      - proxy

  kfk-1:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-1
    ports:
      - "20092:20092"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk-1:13181,zk-2:13181,zk-3:13181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-1:20092
    networks:
      - proxy
 
  kfk-2:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-2
    ports:
      - "30092:30092"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk-1:13181,zk-2:13181,zk-3:13181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-2:30092
    networks:
      - proxy
 
  kfk-3:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-3
    ports:
      - "40092:40092"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk-1:13181,zk-2:13181,zk-3:13181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-3:40092
    networks:
      - proxy

networks:
  proxy:
    driver: bridge